### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Charlie-XIAO**

### CODE REVIEW

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by lesteve** [comment]
@scikit-learn-bot update lock-files

**Comment by lesteve** [comment]
Something that is a bit weird is that there does not seem to be any checks running on the commit after I commented @scikit-learn-bot ...

Not sure why, because ~following your comment it seems to work~ edit it did not see below. I am going to guess this is related to your scikit-learn fork setup, since triggering the CI works fine on `scikit-learn/scikit-learn`.

Edit: actually it did not trigger CI even following your comment, the commit status is only the update-lock-files-pr not the other CI build
image

**Comment by Charlie-XIAO** [comment]
Not sure if this is related: https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by lesteve** [comment]
> Not sure if this is related: [docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks)

Not sure, but to be honest since it works in `scikit-learn/scikit-learn` I think we will be fine.

**Comment by Charlie-XIAO** [comment]
Okay I've reverted testing changes and let's close this.

**Pull request closed without merging**
